# copyright: 2023 EUMETSAT
# license: LICENSE.txt
name: liege-colloquium-23
channels:
  - conda-forge
dependencies:
  - conda-forge::python=3.9
  - conda-forge::netcdf4=1.6.3
  - conda-forge::numpy=1.24.3
  - conda-forge::tensorflow=2.11.0
  - conda-forge::tensorflow-probability=0.19.0
  - conda-forge::tqdm=4.65.0
  - conda-forge::xmltodict=0.13.0
  - conda-forge::xarray=2023.4.2
  - conda-forge::rioxarray=0.14.1  
  - conda-forge::cartopy=0.21.1
  - conda-forge::scikit-image=0.19.3
  - conda-forge::scikit-learn=1.2.2
  - conda-forge::jupyterlab=3.6.3
  - conda-forge::pandas=2.0.1
  - conda-forge::seaborn=0.12.2
  - conda-forge::joblib=1.2.0
  - conda-forge::scipy=1.10.1
  - conda-forge::ipympl=0.9.3
  - conda-forge::ipywidgets=8.0.6
  - conda-forge::requests=2.29.0
  - conda-forge::spectral=0.23.1